[package]
name = "xjvmdbg"
version = "0.1.0"
edition = "2024"

[[bin]]
name = 'xjvmdbg-cli'
path = 'src/bin/main.rs'

[lib]
name = 'xjvmdbg'
path = 'src/lib.rs'

[dependencies]
bitflags = "2.9.1"
byteorder = "1.5.0"
binrw = "0.15.0"
zip = "4.3.0"